// <auto-generated />
using CodeFirstDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstDb.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250220124208_addNullable")]
    partial class addNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstDb.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("CodeFirstDb.Models.ClassCourse", b =>
                {
                    b.Property<int>("ClassCourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassCourseID"));

                    b.Property<int>("ClassID_Fk")
                        .HasColumnType("int");

                    b.Property<int>("CourseID_Fk")
                        .HasColumnType("int");

                    b.HasKey("ClassCourseID");

                    b.HasIndex("ClassID_Fk");

                    b.HasIndex("CourseID_Fk");

                    b.ToTable("ClassCourses");
                });

            modelBuilder.Entity("CodeFirstDb.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CodeFirstDb.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<int?>("ClassId_FK")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("StudentID");

                    b.HasIndex("ClassId_FK");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CodeFirstDb.Models.ClassCourse", b =>
                {
                    b.HasOne("CodeFirstDb.Models.Class", "Class")
                        .WithMany("ClassCourses")
                        .HasForeignKey("ClassID_Fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstDb.Models.Course", "Course")
                        .WithMany("ClassCourses")
                        .HasForeignKey("CourseID_Fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CodeFirstDb.Models.Student", b =>
                {
                    b.HasOne("CodeFirstDb.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId_FK");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("CodeFirstDb.Models.Class", b =>
                {
                    b.Navigation("ClassCourses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CodeFirstDb.Models.Course", b =>
                {
                    b.Navigation("ClassCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
